### ISSUE TITLE
"/github/workspace/build" failed: No such file or directory

### ISSUE THREAD

**Issue by SHSharkar** [AEnterprise/rsync-deploy#1]
rsync: link_stat "/github/workspace/build" failed: No such file or directory (2)
sending incremental file list
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]

sent 18 bytes  received 12 bytes  6.67 bytes/sec
total size is 0  speedup is 0.00
##[error]Docker run failed with exit code 23

**Comment by AEnterprise** [comment]
working fine for me here, seems you are passing it an wrong path, could you show your actions file?

**Comment by SHSharkar** [comment]
Hello,
I have copy-pasted your example snippet for running the script.

You had mentioned  `FOLDER: "build"` which I have not updated. I have just edited the server information to logging to the server.

Also if I leave empty the `FOLDER` variables value, the rsync connects to the server and sending blank information to the server. So, overall, server is connected but the local files were not available for copying the local copy of source codes.

**Comment by SHSharkar** [comment]
OK It seems, without passing the `FOLDER` variables value, the information was correct.

While I `ls` the `$GITHUB_WORKSPACE` directory, the files were showing available to the `/github/workspace` directory. Not in `/github/workspace/build`

![image](https://user-images.githubusercontent.com/12555542/71537988-36b15280-294e-11ea-834f-079c6c30f062.png)

**Comment by AEnterprise** [comment]
ah yeah i'll update that example to specify that's only if you wana sync a specific subfolder, depends on the rest of the build pipeline/tools

**Comment by SHSharkar** [comment]
Thanks for your prompt response. After receiving no solution, I have already created a new GitHub Action for the solution and published it to GitHub Marketplace.

But thanks for your reply.

**Comment by AEnterprise** [comment]
just using ``folder: "/"`` should do the trick to sync from the root
