### ISSUE TITLE
Multiple deployment servers

### ISSUE THREAD

**Issue by dkjensen** [AEnterprise/rsync-deploy#2]
Hello

It would be nice to be able to deploy to multiple servers in a single workflow. Currently it throws an error that the direct currently exists when attempting to add it

`mkdir: cannot create directory '/github/home/.ssh': File exists`

Without testing, this should be possible by adding a flag `-p` to the `mkdir` line to only create the directory if it does not exist

**Comment by AEnterprise** [comment]
i've added the flag, that should do it indeed

**Comment by excing** [comment]
Hello, I found that this new tag version has not created a new tag.

**Comment by sunscreem** [comment]
@AEnterprise FYI - The 1.0 tag doesn't have this fix
