### ISSUE TITLE
Warning: Permanently added '***' (ECDSA) to the list of known hosts.

### ISSUE THREAD

**Issue by llxlr** [AEnterprise/rsync-deploy#3]
![Screenshot_2020-10-04-17-07-58](https://user-images.githubusercontent.com/33483752/95011610-64a58f00-0664-11eb-8771-8005c5134450.png)

**Comment by walterhoson** [comment]
how to config

**Comment by AEnterprise** [comment]
the warning can be ignored, it's just because you connected over ssh and thus it gets added to the known hosts list

if you get errors after that like above then your login credentials are wrong

**Comment by walterhoson** [comment]
My Error is 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).', and action is failed. Is it my sshd_config wrong?

**Comment by AEnterprise** [comment]
that or the variables you set, if you get permission denied then it tried to connect but the provided credentials where refused by the server
